version: 2
jobs:
  build:
    docker:
	# specify the version you desire here
	- image: circleci/python:3.6.1
    steps:
      - checkout
      - run: 
		command: sudo pip install -U selenium		 
      - run: 
		command: sh SauceLabs.sh
