version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
	  - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          FLASK_CONFIG: testing
    steps:
	  - checkout
      - run: 
	   name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar
	 - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.9.1.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
	  - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
	  
	  - run: 
		command: |
            . venv/bin/activate
			pip install sauceclient
	  - run: 
		command: |
            . venv/bin/activate
			pip install smtplib
	  - run: 
		command: |
            . venv/bin/activate
			pip install mimemultipart 
	  - run: 
			sh SauceLabs.sh
	  